(defun find-name-dired-plus (dir pattern)
  (interactive
   "DFind-name (directory): \nsFind-name (separated by space): ")
										;  (find-dired dir (concat find-name-arg " " (shell-quote-argument pattern)))
										;(setq pattern "aa b c")
  (print dir)
  (print pattern)
  (setq pattern-list (split-string pattern " "))
  (setq pattern-final "*")
  (setq i 0)
  (while (< i (length pattern-list))
	(nth i pattern-list)
	(setq s	(nth i pattern-list))
	(message s)
	(setq pattern-final (concat pattern-final s "*"))
	(setq i (+ i 1))
	)
  (print pattern-final)
  (find-name-dired dir pattern-final))
